# Generated by Django 4.0.6 on 2022-07-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tam', '0003_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='status',
            field=models.CharField(choices=[('cooking', 'cooking'), ('awaiting request', 'awaiting request'), ('available', 'available')], max_length=60),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('away', 'away')], max_length=60),
        ),
    ]
