# Generated by Django 4.0.6 on 2022-07-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tam', '0006_preorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
