# Generated by Django 4.0.6 on 2022-07-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tam', '0007_preorder_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
