# Generated by Django 4.0.6 on 2022-07-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tam', '0008_preorder_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorder',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
