# Generated by Django 4.0.6 on 2022-07-19 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tam', '0009_alter_preorder_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preorder',
            name='email',
        ),
    ]
