# Generated by Django 4.0.6 on 2022-07-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tam', '0010_remove_preorder_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorder',
            name='date',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
