# Generated by Django 4.0.6 on 2022-07-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tam', '0011_alter_preorder_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='preorder',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
