# Generated by Django 4.0.6 on 2022-07-20 17:57

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tam', '0012_preorder_email_alter_preorder_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='Profile photo'),
        ),
    ]
