# Generated by Django 4.0.6 on 2022-07-21 04:08

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tam', '0014_alter_profile_address_alter_profile_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Super',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_photo', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='Profile photo')),
                ('bio', models.CharField(max_length=250, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('away', 'away')], max_length=60, null=True)),
            ],
        ),
    ]
