# Generated by Django 4.0.6 on 2022-07-21 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tam', '0016_remove_super_bio_super_about_me'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='mobile_no',
        ),
        migrations.AddField(
            model_name='super',
            name='address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='super',
            name='mobile_no',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
