# Generated by Django 4.0.6 on 2022-07-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tam', '0017_remove_profile_address_remove_profile_mobile_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='super',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='super',
            name='name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
