# Generated by Django 4.0.6 on 2022-07-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tam', '0018_super_email_super_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
                ('email', models.EmailField(default='', max_length=60)),
                ('message', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='super',
            name='mobile_no',
            field=models.IntegerField(null=True),
        ),
    ]
