# Generated by Django 4.0.6 on 2022-07-25 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tam', '0019_contact_alter_super_mobile_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preorder',
            old_name='date',
            new_name='order_date',
        ),
        migrations.RenameField(
            model_name='preorder',
            old_name='name',
            new_name='your_name',
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(default='', max_length=60),
        ),
    ]
