# Generated by Django 4.0.6 on 2022-07-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tam', '0020_rename_date_preorder_order_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorder',
            name='menu',
            field=models.CharField(default='', max_length=60),
        ),
    ]
