# Generated by Django 4.0.6 on 2022-07-25 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tam', '0021_alter_preorder_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preorder',
            old_name='menu',
            new_name='menu_item',
        ),
    ]
