# Generated by Django 4.0.6 on 2022-07-25 04:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tam', '0023_alter_preorder_menu_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preorder',
            name='email',
        ),
        migrations.AddField(
            model_name='preorder',
            name='your_email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='preorder',
            name='your_mobile',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='menu_item',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='preorder',
            name='your_name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
