# Generated by Django 4.0.6 on 2022-07-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tam', '0027_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(default='', max_length=2000)),
                ('author', models.CharField(default='', max_length=60)),
                ('source', models.CharField(default='', max_length=60)),
            ],
        ),
    ]
