# Generated by Django 4.0.6 on 2022-07-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tam', '0028_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='source',
            field=models.URLField(default='', max_length=500),
        ),
    ]
