# Generated by Django 4.0.6 on 2022-07-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tam', '0029_alter_quote_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preorder',
            name='menu_item',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='super',
            name='about_me',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='super',
            name='name',
            field=models.CharField(default='', max_length=60),
        ),
    ]
