# Generated by Django 4.0.6 on 2022-11-06 17:02

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
                ('email', models.EmailField(default='', max_length=60)),
                ('message', models.TextField(default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.CharField(default='', max_length=2000)),
                ('author', models.CharField(default='', max_length=60)),
                ('source', models.URLField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Super',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60)),
                ('about_me', models.CharField(default='', max_length=500)),
                ('profile_photo', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='Profile photo')),
                ('address', models.CharField(max_length=150, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile_no', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('away', 'away')], max_length=60, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(default='', max_length=250)),
                ('profile_photo', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
                ('status', models.CharField(choices=[('active', 'active'), ('away', 'away')], max_length=60, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preorder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_item', models.CharField(default='', max_length=60)),
                ('item_cost', models.IntegerField(null=True)),
                ('your_name', models.CharField(default='', max_length=60)),
                ('your_mobile', models.IntegerField(null=True)),
                ('your_email', models.EmailField(max_length=254, null=True)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=3)),
                ('snap', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Menu photo')),
                ('status', models.CharField(choices=[('cooking', 'cooking'), ('awaiting request', 'awaiting request'), ('available', 'available')], max_length=60)),
                ('cook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ingredients', models.ManyToManyField(to='tam_app.ingredient')),
            ],
        ),
    ]
