# Generated by Django 4.0.6 on 2022-11-07 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tam_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
